version: '3.9'
services:
    db:
      image: postgres:14
      ports:
        - "5432:5432"
      expose:
        - "5432"
      env_file: .env
      volumes:
        - db:/var/lib/postgresql/data
        - ./seed:/docker-entrypoint-initdb.d
    web:
        build: .
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db
volumes:
  db:
