version: '3.9'
services:
    db:
      image: postgres:14
      ports:
        - "5432:5432"
      expose:
        - "5432"
      env_file: .env
      volumes:
        - db:/var/lib/postgresql/data
        - ./seed:/docker-entrypoint-initdb.d
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres && psql --username=postgres --list" ]
        interval: 1s
        timeout: 20s
        retries: 20
    web:
        build: .
        image: app
        env_file: .env
        environment:
          - NODE_ENV=production
#        volumes:
#            - .:/app
        depends_on:
            db:
              condition: service_healthy
volumes:
  db:
