version: '3.9'
services:
    db-test:
      image: postgres:14
      ports:
          - "5432:5432"
      expose:
        - "5432"
      env_file: .env
      volumes:
        - ./seed:/docker-entrypoint-initdb.d
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres && psql --username=postgres --list" ]
        interval: 1s
        timeout: 20s
        retries: 20
    web-test:
        image: node:lts
        working_dir: /app-test
        env_file: .env
        entrypoint: ["npm", "run", "test"]
        environment:
          - NODE_ENV=test
          - POSTGRES_HOST=db-test
        volumes:
            - .:/app-test
        depends_on:
            db-test:
              condition: service_healthy
